import { FunctionComponent } from "react";
import Property1Group2 from "./Property1Group2";
import styles from "./MaskGroup.module.css";
const MaskGroup: FunctionComponent = () => {
  return (
    <div className={styles.maskGroup}>
      <div className={styles.design}>
        <div className={styles.duplicatespot}>
          <div className={styles.fast}>{`FAST. `}</div>
          <div className={styles.simple}>SIMPLE.</div>
          <div className={styles.creative}>CREATIVE.</div>
        </div>
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="320px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="320px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="320px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="437px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="437px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="437px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="554px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="554px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="554px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="671px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="671px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="671px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="788px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="788px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="788px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="905px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="905px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="905px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="1022px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="1022px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="1022px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="1139px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="1139px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="1139px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="1256px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="1256px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="1256px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="1373px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="1373px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="1373px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1727px"
          property1Group2Left="1490px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1791px"
          property1Group2Left="1490px"
        />
        <Property1Group2
          property1Group2Position="absolute"
          property1Group2Top="1855px"
          property1Group2Left="1490px"
        />
      </div>
    </div>
  );
};

export default MaskGroup;
